### ISSUE TITLE
can't find some log

### ISSUE THREAD

**Issue by xiao-an-an** [uiowa-irl/AdGraph#1]
I run the Adgraph(ubuntu16.04) in Vmware, but I can't find some log ,Can you tell me about this question @UmarIqbal

**Comment by UmarIqbal** [comment]
Can you elaborate on this? Do you mean that you are unable to find the generated rendering streams? These files are generated in `{HOME_DIRECTORY}/rendering_stream`. You can find more details on running pre-built binary here https://github.com/uiowa-irl/AdGraph#run-prebuilt-binary

**Comment by xiao-an-an** [comment]
sorry ,I have found this rendering_stream ,Thank you for your answer

**Comment by baejaeho18** [comment]
I have more questions. I also run the AdGraph in VMware(Ubuntu 16.04).
`document.createCDATASection('NOTVEYUNIQUESTRING');`
Does analysis including ml classifier end just by entering the above script into the chromium's dev console? Or is only the graph representation stored?
If feature extraction and ad/non-ad classification are completed, where can I check the results?

Thanks to, @UmarIqbal
