### ISSUE TITLE
How can I check the classified result?

### ISSUE THREAD

**Issue by baejaeho18** [uiowa-irl/AdGraph#3]
I have more questions. I also run the AdGraph in VMware(Ubuntu 16.04).
`document.createCDATASection('NOTVEYUNIQUESTRING');`
Does analysis including ml classifier end just by entering the above script into the chromium's dev console? Or is only the graph representation stored?
If feature extraction and ad/non-ad classification are completed, where can I check the results?

Thanks to, @UmarIqbal

**Comment by UmarIqbal** [comment]
It only stores the graph representation. I have attached the code to process the raw logs (rendering streams). You can use it to extract features for each webpage. Once you generate the feature file, you can use any ML framework/library to train the model.

I used WEKA to train the Random Forest model and I believe the attached folder has some commands to process the feature file with WEKA. However, feel free to use any library, e.g., Scikit, that you're comfortable with to train the model.

Link to code (it will expire in 2 days): https://www.dropbox.com/scl/fi/eg22gqprp5spisfa4jk4m/AdGraphAPI-master.zip?rlkey=k1cig4ctzt3gsj5maxib48g9l&dl=0

Feel free to also send me emails (I am more responsive on email and do not check the GitHub issues regularly). My email is: umar.iqbal@wustl.edu
